#! /usr/bin/env python3

##################
# IMPORT MODULES #
##################

from function import __version__
import rich, collections, rich.progress
import rich_click as click

# Configuration for rich-click CLI help
click.rich_click.USE_RICH_MARKUP = True
click.rich_click.SHOW_METAVARS_COLUMN = False
click.rich_click.APPEND_METAVARS_HELP = True
click.rich_click.HEADER_TEXT = (f"[yellow]/[/][cyan]/[/][yellow]/[/] [bold][link=https://github.com/gjeunen/ALEX]ALEX[/link][/] | v{__version__}")
click.rich_click.FOOTER_TEXT = "See [link=https://github.com/gjeunen/ALEX]https://github.com/gjeunen/ALEX[/] for more details."
click.rich_click.ERRORS_SUGGESTION = f"This is ALEX [cyan]v{__version__}[/]\nFor more help, run '[yellow]alex --help[/]' or visit [link=https://github.com/gjeunen/ALEX]https://github.com/gjeunen/ALEX[/]"
click.rich_click.STYLE_ERRORS_SUGGESTION = ""
click.rich_click.OPTION_GROUPS = {
    "alex": [
        {
            "name": "Input files",
            "options": [
                "--otu-table",
                "--taxonomy-input",
                "--nodes",
                "--names",
            ],
        },
        {
            "name": "Output files",
            "options": [
                "--taxonomy-output",
            ],
        },
    ],
}

@click.command(context_settings=dict(help_option_names=["-h", "--help"]))
@click.option("--otu-table", "otu_table_", help = "count table input file name")
@click.option("--taxonomy-input", "taxonomy_input_", help = "taxonomy input file name")
@click.option("--names", "names_", help = "names.dmp location")
@click.option("--nodes", "nodes_", help = "nodes.dmp location")
@click.option("--taxonomy-output", "taxonomy_output_", help = "taxonomy output file name")
@click.option("--taxonomy-format", "taxonomy_format_", help = "taxonomy classifier")
#@click.option("--blast-format", "blast_format_", default = "6 qaccver saccver ssciname staxid length pident mismatch qcovs evalue bitscore qstart qend sstart send gapopen", help = "format of 'blast-input' file as provided to parameter 'outfmt' in blastn")
#@click.option("--bold-format", "bold_format_", help = "'bold-input' file format: 'summary' (default), 'complete'")
@click.option("--ranks", "ranks_", default = "superkingdom+phylum+class+order+family+genus", help = "ranks included in the taxonomic lineage")
@click.option("--taxa-are-rows", "taxa_are_rows_", default = True, help = "True: column headers = samples (default); False: column headers = taxa")
@click.option("--omit-rows", "omit_rows_", help = "a list of row labels to drop from the frequency table")
@click.option("--omit-columns", "omit_columns_", help = "a list of column labels to drop from the frequency table")

def alex(otu_table, taxonomy_input_, names_, nodes_, taxonomy_output_, taxonomy_format_, ranks_, taxa_are_rows_, omit_rows_, omit_columns_):
    """ALEX (Ancestor Lineage EXplorer)

    
    
    To run ALEX with default settings, use: 
    
    [blue bold]alex --otu-table count.txt --blast-input blast.txt --names names.dmp --nodes nodes.dmp[/]
    """
    console = rich.console.Console(stderr=True, highlight=False)
    console.print(f"\n[yellow]/[/][cyan]/[/][yellow]/[/] [bold][link=https://github.com/gjeunen/tombRaider]tombRaider[/link][/] | v{__version__}\n")
    columns = [*rich.progress.Progress.get_default_columns(), rich.progress.TimeElapsedColumn()]

    # try reading in the files






# blastDict = collections.defaultdict(dict)
# speciesListDict = collections.defaultdict(list)

# with open('zotus_mock_community.fasta.nt.blastn', 'r') as infile:
#     for line in infile:
#         seqID = line.split('\t')[0]
#         speciesName = line.split('\t')[2]
#         pident = float(line.split('\t')[5])
#         qcov = int(line.split('\t')[7])
#         if seqID not in blastDict:
#             blastDict[seqID]['speciesName'] = speciesName
#             blastDict[seqID]['pident'] = pident
#             blastDict[seqID]['qcov'] = qcov
#         else:
#             if blastDict[seqID]['pident'] <= pident and blastDict[seqID]['qcov'] <= qcov and blastDict[seqID]['speciesName'] != speciesName and speciesName not in speciesListDict[seqID] and speciesName != 'N/A':
#                 speciesListDict[seqID].append(speciesName)

# zotuList = []
# with open('zotutable.txt', 'r') as zotufile:
#     for line in zotufile:
#         seqID = line.split('\t')[0]
#         if seqID != 'ID':
#             zotuList.append(seqID)

# for item in zotuList:
#     if item not in blastDict:
#         blastDict[item]['pident'] = 'NA'
#         blastDict[item]['qcov'] = 'NA'
#         blastDict[item]['speciesName'] = 'NA'

# index_map = {v: i for i, v in enumerate(zotuList)}
# blastDict = dict(sorted(blastDict.items(), key=lambda pair: index_map[pair[0]]))

# taxonIdsDict = {}
# taxonNamesDict = {}
# with open('names.dmp', 'r') as infile:
#     for line in infile:
#         sc = line.split('\t')[6]
#         if sc == 'scientific name':
#             taxIdName = line.split('\t|\t')[0]
#             taxonName = line.split('\t|\t')[1].replace(' ', '_')
#             taxonNamesDict[taxIdName] = taxonName
#             taxonIdsDict[taxonName] = taxIdName

# taxonIDsRankDict = {}
# taxonIDsRankUpDict = collections.defaultdict(list)
# with open('nodes.dmp', 'r') as infile:
#     for line in infile:
#         taxonId = line.split('\t|\t')[0]
#         taxonIdUp = line.split('\t|\t')[1]
#         taxonIdRank = line.split('\t|\t')[2]
#         taxonIDsRankDict[taxonId] = [taxonIdRank, taxonIdUp]
#         taxonIDsRankUpDict[taxonIdUp].append(taxonId)

# taxonomicIDlist = []
# for item in blastDict:
#     if blastDict[item]['speciesName'].replace(' ', '_') in taxonIdsDict:
#         blastDict[item]['taxonID'] = taxonIdsDict[blastDict[item]['speciesName'].replace(' ', '_')]
#         if taxonIdsDict[blastDict[item]['speciesName'].replace(' ', '_')] not in taxonomicIDlist:
#             taxonomicIDlist.append(taxonIdsDict[blastDict[item]['speciesName'].replace(' ', '_')])
#     else:
#         blastDict[item]['taxonID'] = 'NA'

# speciesLineagesDict = collections.defaultdict(list)
# for item in taxonomicIDlist:
#     initialItem = item
#     while item != taxonIDsRankDict[item][1]:
#         speciesLineagesDict[initialItem].append([taxonIDsRankDict[item][0], item, taxonNamesDict[item]])
#         item = taxonIDsRankDict[item][1]

# ranksFilteredSpeciesLineagesDict = collections.defaultdict(list)
# ranksNeeded = ['superkingdom', 'phylum', 'class', 'order', 'family', 'genus']
# for lineage in speciesLineagesDict:
#     for rank in ranksNeeded:
#         rankPresent = 0
#         for item in speciesLineagesDict[lineage]:
#             if rank == item[0]:
#                 rankPresent = 1
#                 ranksFilteredSpeciesLineagesDict[lineage].append(item[2])
#         if rankPresent == 0:
#             ranksFilteredSpeciesLineagesDict[lineage].append('NA')

# with open('blastFormattedNew.txt', 'w') as outfile:
#     separator = '\t'
#     outfile.write(f'#OTU ID\t{separator.join(ranksNeeded)}\tspecies\tpident\tqcov\totherSpeciesID\n')
#     for item in blastDict:
#         if blastDict[item]['taxonID'] == 'NA':
#             outfile.write(f'{item}\tNA\tNA\tNA\tNA\tNA\tNA')
#         else:
#             outfile.write(f'{item}\t{separator.join(ranksFilteredSpeciesLineagesDict[blastDict[item]["taxonID"]])}')
#         outfile.write(f'\t{blastDict[item]["speciesName"]}\t{blastDict[item]["pident"]}\t{blastDict[item]["qcov"]}\t{", ".join(speciesListDict[item])}\n')

if __name__ == "__main__":
    alex()
